apiVersion: 1
datasources:
  - name: Garmin-InfluxDB
    uid: garmin_influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: ${INFLUXDB_USER}
    database: ${INFLUXDB_DB}
    isDefault: true
    editable: true
    secureJsonData:
      password: ${INFLUXDB_PASSWORD}
    jsonData:
      httpMode: GET
